# Generated by Django 4.2.6 on 2023-10-06 16:18

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('video', models.FileField(blank=True, max_length=254, null=True, upload_to=video.models.videoFile)),
            ],
        ),
    ]
