# Generated by Django 4.2.6 on 2023-10-08 11:48

import django.core.validators
from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('video', models.FileField(upload_to=video.models.videoFile, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
            ],
        ),
    ]
