# Generated by Django 4.2.6 on 2023-10-06 18:11

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(editable=False, null=True, upload_to=video.models.videoFile),
        ),
    ]
